### ISSUE TITLE
Pre release to-do

### ISSUE THREAD

**Issue by pchhibber** [pchhibber/domain-curation-proto#1]
- [x] Landing page
- [x] rp file restructuring
- [x] workflow in alternate color scheme
- [x] last iteration updates to proto
- [ ] font embedding for proper rendering in all machines
----
- [ ] use page templates and reusable components
- [ ] header color to be more neutral (like TLG)
----
- [x] add images in landing page
- [x] remove extra white space from top of pages
![image](https://cloud.githubusercontent.com/assets/1782334/20866251/9d6138be-ba4e-11e6-9cb6-60449db14c1f.png)
- [x] Under Information Architect Rename Pages. (not on the UI, only in .rp file page name)
Domain Curation-> Domain Curation - Explore
Define -> Domain Curation - Define
- [x] Domain curation page - image to come inside context block
![image](https://cloud.githubusercontent.com/assets/1782334/20866397/ce95c75c-ba52-11e6-91cd-8eda68b1b1d7.png)
- [x] Domain curation page - context and example blocks to come under both the explore and define views
- [x] Domain curation page - for synonyms, patterns and proximate domains, write the words YES, NO, MAYBE only once at the top. Then for each row only have a tick mark
Current view
![image](https://cloud.githubusercontent.com/assets/1782334/20866333/41469378-ba51-11e6-8b22-d057999f91c8.png)
Desired View
![image](https://cloud.githubusercontent.com/assets/1782334/20866349/8a5a07f2-ba51-11e6-8d7d-ae8add170440.png)
- [x] In the landing page, name the users
